# Generated by Django 2.1.2 on 2018-11-05 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
