# Generated by Django 2.1.2 on 2018-11-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_hash_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='hash_id',
        ),
    ]
